module.exports = {
  User: require('./User'),
  Student: require('./Student'),
  Company: require('./Company'),
  College: require('./College'),
  AdminProfile: require('./AdminProfile'),
  Job: require('./Job'),
  Application: require('./Application'),
  Assessment: require('./Assessment'),
  Question: require('./Question'),
  AssessmentSession: require('./AssessmentSession'),
  Score: require('./Score'),
  SkillPassport: require('./SkillPassport'),
  Notification: require('./Notification'),
  AuditLog: require('./AuditLog'),
  Interview: require('./Interview'),
  ProctoringEvent: require('./ProctoringEvent'),
  Otp: require('./Otp'),
  AssessmentAssignment: require('./AssessmentAssignment'),
  PlatformSetting: require('./PlatformSetting'),
  SupportTicket: require('./SupportTicket'),
  StudentSettings: require('./StudentSettings'),
  Drive: require('./Drive'),
  Offer: require('./Offer'),
};
