const fs = require("fs");
const d = "backend-architecture/MERNG";
const w = (f, c) => fs.writeFileSync(d + "/" + f, c);

w("04-jwt-auth-architecture.md", [
  "# JWT Authentication Architecture",
  "",
  "## Token Strategy",
  "- Access Token: 15-minute expiry, stored in memory/localStorage",
  "- Refresh Token: 7-day expiry, stored in DB + localStorage",
  "- Algorithm: HS256 (symmetric)",
  "- Secrets: JWT_SECRET (access), JWT_REFRESH_SECRET (refresh)",
  "",
  "## Authentication Flow",
  "",
  "### Register",
  "POST /auth/register -> Validate -> Hash password (bcrypt) -> Create User + role profile -> Generate JWT tokens -> Store refreshToken -> Return {user, token, refreshToken}",
  "",
  "### Login",
  "POST /auth/login -> Find user -> Compare password (bcrypt) -> Check isActive -> Generate tokens -> Update lastLoginAt -> Return {user, token, refreshToken}",
  "",
  "### Authenticated Request",
  "GET /api/* (Authorization: Bearer <token>) -> Extract token -> Verify JWT -> Decode payload (sub, role) -> Find user -> Check isActive -> Attach to req.user -> Route handler",
  "",
  "### Token Refresh",
  "POST /auth/refresh {refreshToken} -> Verify signature -> Find user -> Compare tokens -> Generate new pair -> Return {token, refreshToken}",
  "",
  "### Logout",
  "POST /auth/logout -> Set refreshToken = null -> Return success",
  "",
  "## Middleware Pattern",
  "- authenticate.js: Verifies JWT, fetches user from DB, sets req.user",
  "- authorize.js: Factory function, checks req.user.role against allowedRoles",
  "",
  "## Security Measures",
  "- Passwords hashed with bcrypt (12 salt rounds)",
  "- Refresh token rotation on each refresh",
  "- Password/refreshToken use select: false",
  "- Express-rate-limit on auth routes",
  "- Helmet security headers",
  "- toJSON() strips sensitive fields",
].join("\n"));
console.log("04 done");

w("05-rbac-architecture.md", [
  "# Role-Based Access Control (RBAC) Architecture",
  "",
  "## Role Definitions",
  "| Role | Description | Profile Model |",
  "|------|-------------|---------------|",
  "| student | Job seeker | Student.js |",
  "| company | Job poster | Company.js |",
  "| college | Placement coordinator | College.js |",
  "| admin | Super admin | AdminProfile.js |",
  "",
  "## Permission Matrix",
  "| Resource | student | company | college | admin |",
  "|----------|---------|---------|---------|-------|",
  "| Own Profile | CRUD | CRUD | CRUD | CRUD |",
  "| Browse Jobs | R | R | R | R |",
  "| Post Jobs | - | CRUD | - | CRUD |",
  "| Apply to Jobs | CRUD | - | - | - |",
  "| View Applications | Own | Own | - | All |",
  "| Update App Status | - | CRUD | - | - |",
  "| Take Assessments | CRUD | - | - | - |",
  "| View Scores | Own | - | Agg | All |",
  "| Notifications | Own | Own | Own | All |",
  "| Audit Logs | - | - | - | CRUD |",
  "| Manage Users | - | - | - | CRUD |",
  "",
  "## Data Scoping",
  "- Student: Applications scoped to student._id",
  "- Company: Jobs scoped to company._id, Applications for their jobs",
  "- Notifications: Always scoped to userId = req.user._id",
  "",
  "## Middleware Usage",
  "router.get('/', authenticate, authorize('student', 'company'), handler);",
  "authorize() is a factory returning configured middleware. Returns 403 on failure.",
].join("\n"));
console.log("05 done");

w("06-assessment-engine.md", [
  "# Assessment Engine Architecture",
  "",
  "## Start Assessment",
  "POST /assessments/:id/start -> Find assessment + questions -> Check no existing session -> Create session (pending) -> Shuffle questions -> Strip answers -> Return {sessionId, questions, duration, startedAt}",
  "",
  "## Submit Assessment",
  "POST /assessments/:id/submit {answers[]} -> Find session -> Validate in_progress -> Check timer -> Grade each answer -> Calculate score -> Determine grade -> Create Score -> Update SkillPassport -> Return result",
  "",
  "## View Results",
  "GET /assessments/:id/results -> Find latest Score doc -> Return breakdown",
  "",
  "## Scoring",
  "- Percentage = (earnedPoints / totalPoints) * 100",
  "- Grade: >=90% Excellent, >=75% Good, >=50% Average, else Needs Improvement",
  "- Passed: percentage >= passingScore (default 60)",
  "",
  "## Timer Enforcement",
  "- Server-side: startedAt + duration compared on submit",
  "- Client-side: Countdown timer with auto-submit at 0",
  "- Session states: pending -> in_progress -> completed | timed_out",
  "",
  "## Anti-Cheat",
  "- Correct answers stripped from client",
  "- Questions shuffled per attempt",
  "- Server-side time limit enforced",
  "- One active session per assessment per student",
].join("\n"));
console.log("06 done");

w("07-job-management.md", [
  "# Job Management Architecture",
  "",
  "## Flow",
  "- Create: POST /jobs -> Find company -> Validate -> Create Job -> Notify",
  "- Browse: GET /jobs?skills=&type=&search= -> Build filter -> Paginate (20) -> Populate company",
  "- Update: PUT /jobs/:id -> Find by id+company -> Update -> Return",
  "",
  "## Search & Filter",
  "- Status: active, closed, draft",
  "- Type: Full-time, Part-time, Internship, Contract",
  "- Skills: comma-separated (skills=React,Node.js)",
  "- Text: regex on title (case-insensitive)",
  "- Pagination: page, limit, total, pages",
  "- Sort: postedAt descending",
  "- Populate: companyId -> companyName, industry, logoUrl, location",
].join("\n"));
console.log("07 done");

w("08-application-management.md", [
  "# Application Management Architecture",
  "",
  "## Flow",
  "- Submit: POST /applications -> Find student -> Check no duplicate -> Verify job -> Create App -> Increment count -> Notify",
  "- View: GET /applications -> Filter by role -> Populate job+student",
  "- Update Status: PUT /applications/:id/status -> Find app -> Update -> Notify student",
  "",
  "## Pipeline",
  "Applied -> Shortlisted -> Interview -> Accepted",
  "Any stage can go to Rejected",
  "",
  "## Rules",
  "- No duplicates: unique index on jobId+studentId",
  "- Student profile required",
  "- Status change triggers notification",
  "- applicantsCount auto-incremented on create",
].join("\n"));
console.log("08 done");

w("09-notification-architecture.md", [
  "# Notification Architecture",
  "",
  "## Types: info, success, warning, error",
  "",
  "## Triggers",
  "- Application submitted -> Company (info)",
  "- Status changed -> Student (varies)",
  "- Assessment available -> Student (info)",
  "- Assessment completed -> Student (success)",
  "- Profile incomplete -> Student (warning)",
  "",
  "## Schema",
  "- userId, title, message, type (enum), isRead (default false), link, metadata (Mixed)",
  "- Indexes: {userId:1, isRead:1}, {createdAt:-1}",
  "",
  "## API",
  "- GET / -> List + unreadCount",
  "- PUT /:id/read -> Mark one as read",
  "- PUT /read-all -> Mark all as read",
].join("\n"));
console.log("09 done");

w("10-audit-log-architecture.md", [
  "# Audit Log Architecture",
  "",
  "## Schema",
  "- userId (ref User), action, resource, resourceId, details, ipAddress, userAgent, metadata (Mixed)",
  "- Indexes: {userId:1}, {action:1}, {createdAt:-1}",
  "",
  "## Audited Actions",
  "- REGISTER, LOGIN, LOGOUT, TOKEN_REFRESH",
  "- CREATE_JOB, UPDATE_JOB, DELETE_JOB",
  "- APPLY, UPDATE_APP_STATUS",
  "- START_ASSESSMENT, SUBMIT_ASSESSMENT",
  "- ADMIN_DEACTIVATE_USER",
  "",
  "## Rules",
  "- Write-only (no update/delete)",
  "- Admin-only access",
  "- IP from req.ip or x-forwarded-for",
  "- Indexed by createdAt for efficient queries",
].join("\n"));
console.log("10 done");

// Verify
const f2 = require("fs");
const files = f2.readdirSync(d).filter(f => f.endsWith(".md")).sort();
files.forEach(f => console.log("  " + f + " (" + f2.statSync(d+"/"+f).size + " bytes)"));
